# Generated by Django 4.0.6 on 2022-07-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('image', models.URLField(verbose_name='Картинка')),
                ('release_date', models.DateTimeField(verbose_name='Дата выпуска')),
                ('lte_exists', models.BooleanField(verbose_name='Наличие LTE')),
                ('slug', models.SlugField(max_length=255, verbose_name='URL')),
            ],
        ),
    ]
